# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 685aa2377af7216058bad6840227cceb62b913e0c0b65140a4be3e2af4d842ad7b784677403e678599e0f7e5da42276bc4d3216937ac90c8809f4a9b9fa6b235

test:
  secret_key_base: fc7a74b2073df021581bd9f24d506eb14aac251bba9e9c5fc5dcccdb62407e796e50914398cc215f21d1c61cc8b8d5e15172f65b318fc2e3226809e49937fb13

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
